#pragma once

namespace rage {
	enum diagSeverity {
		DIAG_SEVERITY_FATAL,
		DIAG_SEVERITY_ASSERT,
		DIAG_SEVERITY_ERROR,
		DIAG_SEVERITY_WARNING,
		DIAG_SEVERITY_DISPLAY,
		DIAG_SEVERITY_DEBUG1,
		DIAG_SEVERITY_DEBUG2,
		DIAG_SEVERITY_DEBUG3,
		DIAG_SEVERITY_COUNT
	};
}