#pragma once

namespace rage {
	enum netHttpAbortReason {
		NET_HTTPABORT_NONE                                 = 0,
		NET_HTTPABORT_COMMIT_FAILED                        = 1,
		NET_HTTPABORT_CANCELED                             = 2,
		NET_HTTPABORT_REQUEST_TIMED_OUT                    = 3,
		NET_HTTPABORT_RESOLVE_HOST_FAILED                  = 4,
		NET_HTTPABORT_RESOLVING_HOST_FAILED                = 5,
		NET_HTTPABORT_CONNECT_HOST_FAILED                  = 6,
		NET_HTTPABORT_CONNECTING_HOST_FAILED               = 7,
		NET_HTTPABORT_SEND_HEADER_FAILED                   = 8,
		NET_HTTPABORT_RECEIVE_HEADER_FAILED                = 9,
		NET_HTTPABORT_PROCESS_RESPONSE_HEADER_FAILED       = 10,
		NET_HTTPABORT_RESPONSE_NO_LOCATION_LENGTH          = 11,
		NET_HTTPABORT_RESPONSE_REDIRECT_FAILED             = 12,
		NET_HTTPABORT_RESPONSE_GET_LOCATION_FAILED         = 13,
		NET_HTTPABORT_RESPONSE_UNHANDLED_TRANSFER_ENCODING = 14,
		NET_HTTPABORT_RESPONSE_PARSE_CONTENT_LENGTH_FAILED = 15,
		NET_HTTPABORT_READ_BODY_FAILED                     = 16,
		NET_HTTPABORT_CONSUME_BODY_FAILED                  = 17,
		NET_HTTPABORT_CHUNK_OPERATION_FAILED               = 18,
		NET_HTTPABORT_ALLOCATE_CHUNK_FAILED                = 19,
		NET_HTTPABORT_SEND_CHUNK_FAILED                    = 20,
		NET_HTTPABORT_XBL_RECEIVE_HEADER_FAILED            = 21,
		NET_HTTPABORT_XBL_RECEIVE_BODY_FAILED              = 22,
		NET_HTTPABORT_PROCESS_BOUNCE_CONTENT_FAILED        = 23,
		NET_HTTPABORT_READ_BODY_ONCE_FAILED                = 24,
		NET_HTTPABORT_XBOX_AUTH_TOKEN_FAILED               = 25,
	};
}