#pragma once

namespace rage {
	enum rlRosEnvironment {
		// DO NOT CHANGE THE ORDER OF THESE ENVIRONMENTS - BACKWARDS COMPATIBILITY
		RLROS_ENV_UNKNOWN = -1,
		RLROS_ENV_RAGE,
		RLROS_ENV_DEV,
		RLROS_ENV_CERT,
		RLROS_ENV_PROD,
		// ADD NEW ENVIRONMENTS TO THE END OF THIS LIST - BACKWARDS COMPATIBILITY
		RLROS_ENV_CERT_2,
		RLROS_ENV_CI_RAGE
	};
}